# Generated by Django 4.2.5 on 2023-12-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='User',
        ),
        migrations.RemoveField(
            model_name='review',
            name='User',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='User',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
